server.port=8081

spring.kafka.template.default-topic=com.ng.vela.even.card_verified

spring.kafka.consumer.bootstrap-servers=localhost:9092
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.Deserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.Deserializer
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.group-id=vela